/**
 * TypeScript type definitions for the Relationship Decision Engine
 * 
 * This file contains all the core data types used throughout the application.
 */

/**
 * Represents a relationship with a person
 * 
 * @property id - Unique identifier (will be generated by database)
 * @property person_name - Name of the person in the relationship
 * @property type - Type/category of the relationship (e.g., "friend", "colleague", "family")
 * @property notes - Optional notes about the relationship
 * @property created_at - Timestamp when the relationship was created
 */
export type Relationship = {
  id?: string;
  person_name: string;
  type: string;
  notes?: string;
  created_at?: string;
};

/**
 * Represents an event logged for a relationship
 * 
 * @property id - Unique identifier (will be generated by database)
 * @property relationship_id - ID of the relationship this event belongs to
 * @property event_type - Type of event (e.g., "meeting", "call", "message")
 * @property description - Description of what happened in this event
 * @property created_at - Timestamp when the event occurred
 */
export type Event = {
  id?: string;
  relationship_id: string;
  event_type: string;
  description: string;
  created_at?: string;
};

/**
 * Represents an AI-generated insight about a relationship
 * 
 * This is the result of analyzing a relationship and its events using OpenAI.
 * 
 * @property id - Unique identifier (will be generated by database)
 * @property relationship_id - ID of the relationship this insight is for
 * @property summary - Brief summary of the relationship
 * @property pattern - Patterns identified in the relationship events
 * @property risk_score - Risk score (0-100, where higher means more risk)
 * @property growth_score - Growth score (0-100, where higher means more growth potential)
 * @property recommended_action - Recommended action to take
 * @property suggested_message - Suggested message to send to the person
 * @property created_at - Timestamp when the insight was generated
 */
export type Insight = {
  id?: string;
  relationship_id: string;
  summary: string;
  pattern: string;
  risk_score: number;
  growth_score: number;
  recommended_action: string;
  suggested_message: string;
  created_at?: string;
};

